# REQUIRES CANVAS DATA SCRAPE TO BE RUN FIRST TO GET COURSES (change line 1 to match file name))
import re
import requests
from time import sleep
from  datetime import datetime, timezone
from bs4 import BeautifulSoup
from selenium import webdriver
import gradescopeapi.classes._helpers._assignment_helpers as gscope_helpers

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[2]))

from config import supabase

FIFTEEN_122_KEYWORDS = ("15-122", "Principles of Imperative Computation")
CANVAS_BASE_URL = "https://canvas.cmu.edu"
GRADESCOPE_TOOL_NAME = "Gradescope LTI 1.3"
FIFTEEN_122_WEBSITE = "https://www.cs.cmu.edu/~15122/"
COURSEWORK_SECTIONS = {
    "Programming Assignments": "programming-assignment",
    "Practice Problems": "practice-problem",
    "Check-Ins": "check-in",
}


def is_15122_course(course):
    course_text = " ".join(
        str(course.get(key, ""))
        for key in ("name", "course_code", "original_name")
    )
    return any(keyword.lower() in course_text.lower() for keyword in FIFTEEN_122_KEYWORDS)


def scrape_15122_coursework(url=FIFTEEN_122_WEBSITE):
    """Return coursework due dates embedded in the 15-122 page source.

    The visible coursework tables are generated by JavaScript. The source page
    stores the underlying dates in C.addHw and C.addExam calls.
    """

    response = requests.get(url, timeout=20)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    coursework = {section: [] for section in COURSEWORK_SECTIONS}

    source = "\n".join(script.get_text() for script in soup.find_all("script"))
    source = re.sub(r"(?m)^\s*//.*$", "", source)
    section_by_type = {
        "PR": ("Practice Problems", 0),
        "PG": ("Programming Assignments", 1),
        "CH": ("Check-Ins", 1),
    }

    for function, pattern in (
        ("addHw", r"C\.addHw\(\s*['\"](?P<type>[^'\"]+)['\"]\s*,\s*(?P<year>\d{4})\s*,\s*(?P<month>\d{1,2})\s*,\s*(?P<day>\d{1,2})"),
        ("addExam", r"C\.addExam\(\s*['\"](?P<type>[^'\"]+)['\"]\s*,\s*(?P<year>\d{4})\s*,\s*(?P<month>\d{1,2})\s*,\s*(?P<day>\d{1,2})"),
    ):
        for match in re.finditer(pattern, source):
            section_info = section_by_type.get(match.group("type"))
            if section_info is None:
                continue
            section, first_number = section_info

            date = datetime(
                int(match.group("year")),
                int(match.group("month")),
                int(match.group("day")),
            ).date()
            coursework[section].append({"date": date.isoformat()})

    for entries in coursework.values():
        entries.sort(key=lambda entry: entry["date"])

    for section, entries in coursework.items():
        prefix, first_number = {
            "Practice Problems": ("PR", 0),
            "Programming Assignments": ("PG", 1),
            "Check-Ins": ("CH", 1),
        }[section]
        for index, entry in enumerate(entries):
            entry["name"] = f"{prefix}{first_number + index}"

    return coursework


def get_paginated_session(session, url, HEADERS):
    sleep(1)
    results = []
    while url:
        r = session.get(url, headers=HEADERS)
        r.raise_for_status()
        results.extend(r.json())
        url = r.links.get("next", {}).get("url")
    return results


def get_active_classes(courses):
    curr_date = datetime.now(timezone.utc)
    active_courses = []
    for course in courses:
        term = course.get("term")
        if not term:
            continue

        end_at_str = term.get("end_at")
        if end_at_str is None:
            active_courses.append(course)
            continue

        end_at = datetime.fromisoformat(end_at_str.replace("Z", "+00:00"))
        if end_at > curr_date:
            active_courses.append(course)
    return active_courses


def get_class_ext_tools(session, course_id, HEADERS):
    try:
        return get_paginated_session(
            session,
            f"{CANVAS_BASE_URL}/api/v1/courses/{course_id}/external_tools/visible_course_nav_tools",
            HEADERS,
        )
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 403:
            return []
        raise


def get_gscope_url(session, course_id, tool, HEADERS):
    launch_url = f"{CANVAS_BASE_URL}/api/v1/courses/{course_id}/external_tools/sessionless_launch?url={tool.get('url', '')}"
    r = session.get(launch_url, headers=HEADERS)
    if r.status_code != 200:
        return ""
    return r.json().get("url", "")


def can_launch_15122(session, courses, HEADERS):
    for course in get_active_classes(courses):
        if not is_15122_course(course):
            continue

        course_id = course["id"]
        ext_tools = get_class_ext_tools(session, course_id, HEADERS)
        for tool in ext_tools:
            if GRADESCOPE_TOOL_NAME not in tool.get("name", ""):
                continue

            gscope_url = get_gscope_url(session, course_id, tool, HEADERS)
            if not gscope_url:
                continue

            response = session.get(gscope_url, headers=HEADERS)
            if response.status_code == 200:
                return True

    return False


def is_enrolled_in_15122(CANVAS_TOKEN):
    """Return True when the Canvas user can launch the 15-122 Gradescope course."""

    session = requests.Session()
    HEADERS = {"Authorization": f"Bearer {CANVAS_TOKEN}"}
    courses = get_paginated_session(
        session,
        f"{CANVAS_BASE_URL}/api/v1/courses?include[]=term",
        HEADERS,
    )
    return can_launch_15122(session, courses, HEADERS)


def write_15122_coursework_to_supabase(user_id, coursework):
    existing = (
        supabase.table("assignments_duplicate")
        .select("assignment_id, status")
        .eq("user_id", user_id)
        .eq("platform", "15-122")
        .execute()
    )
    existing_status = {
        row["assignment_id"]: row.get("status", False)
        for row in (existing.data or [])
    }

    records = []
    course_name = "15-122: Principles of Imperative Computation"
    for entries in coursework.values():
        for entry in entries:
            assignment_id = f"{user_id} 15122 {entry['name']}"
            records.append({
                "assignment_id": assignment_id,
                "assignment_name": entry["name"],
                "course_name": course_name,
                "due_date": entry["date"],
                "points_possible": None,
                "retrieved_at": datetime.now(timezone.utc).isoformat(),
                "user_id": user_id,
                "status": existing_status.get(assignment_id, False),
                "platform": "15-122",
            })

    if records:
        supabase.table("assignments_duplicate").upsert(
            records,
            on_conflict="assignment_id",
        ).execute()


def send_gradescope_to_supabase(user_id, CANVAS_TOKEN):
    def load_gscope_cookies(driver, session):
        for cookie in session.cookies:
            try:
                driver.add_cookie({
                    'name': cookie.name,
                    'value': cookie.value,
                })
            except Exception:
                pass

    def gscope_login(gscope_url, driver, session, HEADERS):
        # Pre-load cookies from session before navigating
        driver.get("https://www.gradescope.com")  # Navigate to domain first
        load_gscope_cookies(driver, session)  # Load cookies into Selenium session

        driver.get(gscope_url)
        sleep(5)
        final_url = driver.current_url
        print(f"Final URL: {final_url}")

        # Grab cookies from response and use with requests
        for cookie in driver.get_cookies():
            session.cookies.set(cookie['name'], cookie['value'])                
        
        response = session.get(final_url, headers=HEADERS)
        print(f"Status: {response.status_code}")
        return response

    def write_assignments_to_database(user_id, gradescope_data):
        assignment_dict = [dict((vars(Assignment).items())) for Assignment in gradescope_data]
        for a in assignment_dict:
            a["course_name"] = course_name
            a["course_code"] = course.get("course_code", "---")
            a["course_id"] = course_id
            assignment_record = {
                "course_name": a["course_name"],
                "assignment_id": f"{user_id} gradescope {a['assignment_id']}",
                "assignment_name": a["name"],
                "due_date": a["due_date"].isoformat() if a["due_date"] else None,
                "points_possible": a.get("max_grade"),
                "retrieved_at": datetime.now(timezone.utc).isoformat(),
                "user_id": user_id,
                "status": False,
                "platform": "Gradescope"
            }
        # Insert into Supabase
            print(assignment_record)
            try:
                response = supabase.table("assignments_duplicate").upsert(assignment_record,
                                                                on_conflict="assignment_id",
                                                                ignore_duplicates=True).execute()
                # if not response.data:
                #     print("Supabase insert failed:", response)
            except Exception as e:
                print("Supabase insert exception:", e)

    session = requests.Session()
    canvas_url = f"{CANVAS_BASE_URL}/api/v1/courses?include[]=term"
    HEADERS = {
       "Authorization": f"Bearer {CANVAS_TOKEN}"
       }

    courses = get_paginated_session(session, canvas_url, HEADERS)
    active_courses = get_active_classes(courses)
    coursework_15122_synced = False

    for course in active_courses:
        course_id = course["id"]
        course_name = course.get("name", "Unnamed Course")

        ext_tools = get_class_ext_tools(session, course_id, HEADERS)
        if not ext_tools:
            continue

        for tool in ext_tools:
            if GRADESCOPE_TOOL_NAME in tool.get("name", ""):
                print(f"\n{course_name}")
                print("-" * len(course_name))
                print("Gradescope integration detected. Attempting login...")

                # Access launch URL for Gradescope
                gscope_url = get_gscope_url(session, course_id, tool, HEADERS)
                if not gscope_url:
                    print("Failed to access Gradescope launch URL.")
                    continue
                print("Successfully accessed Gradescope launch URL.")

                # Handle redirects and extract the final URL after login.
                driver = webdriver.Chrome()  # Ensure chromedriver is in PATH
                try:
                    response = gscope_login(gscope_url, driver, session, HEADERS)
                    soup = BeautifulSoup(response.text, 'html.parser')
                    gradescope_data = gscope_helpers.get_assignments_student_view(soup)

                    if gradescope_data:
                        write_assignments_to_database(user_id,gradescope_data)

                    if (
                        is_15122_course(course)
                        and response.status_code == 200
                        and not coursework_15122_synced
                    ):
                        coursework = scrape_15122_coursework()
                        write_15122_coursework_to_supabase(user_id, coursework)
                        coursework_15122_synced = True
                finally:
                    driver.quit()
